### ISSUE TITLE
Dictionary encoding example ASP is incomplete

### ISSUE THREAD

**Issue by pwrose** [rcsb/mmtf#18]
There is an O atom missing in the ASP dictionary example. Also, why are the formal charges all zero?

**Comment by arose** [comment]
Added the oxygen, see e863b70644e4e37f2196a89235c68aea8f1f7f80, however note that this is purely cosmetical, the data in there was from a real-life example where an oxygen was simply missing.

The formal charges are zero because they are zero in the [Chemical Component Dictionary](http://www.wwpdb.org/data/ccd) where our biojava-based mmtf generator gets its data from.
