### ISSUE TITLE
1R9V peptide bonds missing for DNM residue

### ISSUE THREAD

**Issue by speleo3** [rcsb/mmtf#20]
1R9V residue 9 (DNM) is not connected.
 
![1r9v-dnm-missing-peptide-bonds](https://cloud.githubusercontent.com/assets/1239490/22998797/74679728-f3a6-11e6-8518-59b61ae13723.png)

**Comment by josemduarte** [comment]
Here the chemical component dictionary is quite clear (see https://files.rcsb.org/ligands/view/DNM.cif):

```
_chem_comp.type                                  NON-POLYMER
```
i.e. DNM is not peptide-linked following its definition (for peptide-linked groups the type is `L-PEPTIDE LINKING`). 

If you think the group should be linked, then this is an error in the annotation or deposition. To me it does look like an error since DNM is assigned to chain identifier `A` which belongs to the 1 entity in that entry. The entity is annotated as polymeric, and the other residues in it do have `L-PEPTIDE LINKING` as type.

We are going to raise this issue (and others already reported) with the annotation team at RCSB PDB to see if the data can be corrected.

**Comment by xbdsch** [comment]
DNM updated to 
_chem_comp.type                                  "D-PEPTIDE LINKING" 
_chem_comp.pdbx_type                             ATOMP
The update will show in public on 3/8/2017

**Comment by josemduarte** [comment]
Thanks @xbdsch !

**Comment by speleo3** [comment]
Great, thank you!

**Comment by speleo3** [comment]
@xbdsch where is the proper place to report such primary data issues?

**Comment by xbdsch** [comment]
If it's regarding rcsb website feature, please email info@rcsb.org
If it's regarding question on file content or annotation, please email deposit-help@mail.wwpdb.org
