### ISSUE TITLE
[feature request] Please support the secondary structure information and other essential information supported by the pdb format

### ISSUE THREAD

**Issue by yurivict** [rcsb/mmtf#41]
Continuing from https://github.com/rcsb/mmtf-cpp/issues/28

> The recently added extra fields might be a solution for any additional data you would like to store.

I was downloading data from the PDB database in the MMTF format, but it lacks the secondary structure information.

This also makes the "PDB archive size comparison" graph on https://mmtf.rcsb.org/ invalid since the PDB format has more information in it.

**Comment by pwrose** [comment]
The mmtf files do contain secondary structure information, however, it has
been recalculated using the DSSP implementation in BioJava. This was done
since the original secondary structure information has not been
consistently assigned, e.g., using different software, different, version,
even done manually for older structures. To provide consistency, we have
recalculated secondary structure assignments (see:
https://github.com/rcsb/mmtf/blob/master/spec.md#secstructlist).

Formula information is not included since it can be easily calculated. The
MMTF format is designed to avoid storing redundant information and it only
contains the most often used data, it's not a replacement for the other
formats. On the other hand, MMTF contains additional information not found
in PDB or PDBx/mmCIF files, e.g., bonds and bond orders for the entire
structure, including ligands.

For more details what data are included in MMTF files, please see:
https://doi.org/10.1371/journal.pcbi.1005575

**Comment by yurivict** [comment]
@pwrose  Thank you for the clarification.
