### ISSUE TITLE
Incomplete definition of the groupTypeList field

### ISSUE THREAD

**Issue by cxn-pkovacs** [rcsb/mmtf#45]
The definition of [groupTypeList](https://github.com/rcsb/mmtf/blob/v1.0/spec.md#grouptypelist) uses the term `groupTypeId`. It is unclear where the term `groupTypeId` itself is defined.

**Comment by pwrose** [comment]
Good catch. There is a typo in v1.0 spec.

The world groupTypeId should be changed to groupTypeList. This has been
fixed in the master branch, see
https://github.com/rcsb/mmtf/blob/master/spec.md

The description should read:
*Description*: Array of pointers to groupType entries in groupList by their
keys. One entry for each residue, thus the number of residues is equal to
the length of the groupTypeList field.

**Comment by pwrose** [comment]
Typo has been corrected in master branch.
