### ISSUE TITLE
retinal missing double-bond connection to lysine in GPCR 1F88

### ISSUE THREAD

**Issue by BobHanson** [rcsb/mmtf#5]
While it is excellent to be able to show double bonds now within groups, there are a few cases, such as Schiff bases between an aldehyde and lysine, where a double bond is needed linking two groups. If all the other double bonds are present, but this one is missing, users will rightly consider it a bug.  See 1F88.mmtf  

![1f88_ret](https://cloud.githubusercontent.com/assets/17748315/14783489/989ebd90-0ab5-11e6-9200-6b8cb716c089.png)

**Comment by arose** [comment]
Thanks for pointing this out!

**Comment by arose** [comment]
We currently rely on mmcif files and the chemical component dictionary to get bond information. The Schiff base double bond is not really given in the mmcif file, that is the [_struct_conn.pdbx_value_order](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx.dic/Items/_struct_conn.pdbx_value_order.html) is mostly empty. However, the Schiff base bond seems to be given twice, in both directions, so one could infer the order from that, but we have to check if that is intended and consistent across the archive.

**Comment by BobHanson** [comment]
That would be great if it turns out to be that easy.

**Comment by arose** [comment]
> However, the Schiff base bond seems to be given twice, in both directions, so one could infer the order from that, but we have to check if that is intended and consistent across the archive.

I looked at it again and the bond is only given twice because there are two retinal and rhodopsin molecules in that file.

There is a mmcif [field](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx.dic/Items/_struct_conn.pdbx_value_order.html) for the bond order but that seems rarely set. We can suggest setting GPCR-Retinal bonds for a remediation round, but that is a thing all the wwpdb partners need to decide.

**Comment by arose** [comment]
Has been reported, if and when it is remediated the data will automatically be used.
